# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3309/db_hero
#     username: root
#     password: MySQL123
#     driver-class-name: com.mysql.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#     database: mysql
#     database-platform: org.hibernate.dialect.MySQLDialect
